### ISSUE TITLE
Imported keys have algorithm name that is lower case

### ISSUE THREAD

**Issue by seebees** [microsoft/MSR-JavaScript-Crypto#1]
Looking here:
https://github.com/microsoft/MSR-JavaScript-Crypto/blob/9d2868ab687df60ddbdbb62cc17f4cb8ef7adaa3/scripts/subtle/subtleInterface.js#L123
the algorithm name is normalized to lower case.

But looking here: https://www.w3.org/TR/WebCryptoAPI/#dfn-supportedAlgorithms
All the algorithm names are upper case.
It would be nice if the imported key algorithm name matched the value specification name.

**Comment by ljoy913** [comment]
That's a hold over from when IE11 was the only browser supporting the Web Crypto API.  For whatever reason they used all lower-case on their key properties.  We were emulating that behavior as a polyfill.
I'll update those labels to be upper case. Thanks.

**Comment by seebees** [comment]
Thanks much!

**Comment by ljoy913** [comment]
Normalized the algorithm identifier names to upper case (e.g. "RSA-OAEP").  These names appear on the algorithm property of CryptoKey objects.
