### ISSUE TITLE
Plans to support AES-KW key wrapping alg?

### ISSUE THREAD

**Issue by dmitrizagidulin** [microsoft/MSR-JavaScript-Crypto#16]
Are there any plans for supporting the [`AES-KW`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/wrapKey#aes-kw) WebCryptography API algorithm? 

Thanks.

**Comment by ljoy913** [comment]
I'll add it.  Might take a week or so with testing.

**Comment by dmitrizagidulin** [comment]
Thank you so much!

**Comment by ljoy913** [comment]
I have the algorithm added and working.  I'm still putting tests together.  I had to add some additional key-export support that was missing - so it was a bigger job than anticipated.  A few more days, then I'll push the update.

**Comment by ljoy913** [comment]
I pushed an update to version 1.6.6 that adds the AES-KW algorithm

**Comment by ljoy913** [comment]
Added

**Comment by dmitrizagidulin** [comment]
@ljoy913 - thank you so much, this is incredibly helpful!
