### ISSUE TITLE
Minified library does not support IE8

### ISSUE THREAD

**Issue by lyswhut** [microsoft/MSR-JavaScript-Crypto#2]
Minified library called `Promise.catch()` causing an error to be thrown under IE8

![1](https://user-images.githubusercontent.com/20365169/87401345-97ebfb00-c5ec-11ea-8077-12d60a9a53da.png)

Full library can work normally.

Now I switch to `gulp-uglify` + `gulp-rename` and resume working after rebuilding
```js
// gulpfile.js
// Minify the new bundle to a .min.js file.
function minifyBundle() {
    return gulp.src(
        [
            "lib/msrcrypto.js"
        ])
        .pipe(rename({ suffix: '.min' }))
        .pipe(uglify({
            ie8: true
        }))
        .pipe(gulp.dest("lib"));    // write the file to the lib folder
}
```
![image](https://user-images.githubusercontent.com/20365169/87406738-b7d2ed00-c5f3-11ea-8c38-b96257c68096.png)

**Comment by ljoy913** [comment]
Thanks for letting me know.  I'll take a look at this and update my gulp calls.  Looks like the minifier is too helpful in this case.

**Comment by ljoy913** [comment]
Updated the gulp minifier settings to not compress the quoted 'catch' property.  Updated the entropy file to prevent the mangler from losing a global reference in IE8.
